name: Upgrade ABIs

on:
  pull_request

env:
  ARBISCAN_API_KEY: ${{secrets.ARBISCAN_API_KEY}}
  ARBITRUM_TESTNET_GOERLI_RPC_URL: ${{ secrets.ARBITRUM_TESTNET_GOERLI_RPC_URL}}
  ARBITRUM_TESTNET_RPC_URL: ${{ secrets.ARBITRUM_TESTNET_RPC_URL}}
  ARBITRUM_TESTNET_SEPOLIA_RPC_URL: ${{ secrets.ARBITRUM_TESTNET_SEPOLIA_RPC_URL}}
  TESTNET_DEPLOYER_PK: ${{secrets.TESTNET_DEPLOYER_PK}}

permissions:
  contents: write

jobs:
  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Determine Branch Name
        id: set_branch
        run: |          
            echo "${{ github.event.pull_request.head.ref }}"
            echo "${{ github.head_ref }}"

      # - name: Install dependencies
      #   run: yarn install

      # - name: Clear cache
      #   run: yarn hardhat clean --config hardhat-continuous-deployment.config.js

      # - name: Compile contracts
      #   run: yarn hardhat compile --config hardhat-continuous-deployment.config.js

      # - name: Fetch repository
      #   run: git fetch

      # - name: Deploy contracts on Arbitrum Sepolia
      #   run: yarn upgrade:sepolia --config hardhat-continuous-deployment.config.js

      # - name: Commit ABIs
      #   env:
      #     COMMIT_MSG: "ci(deployments): upgrade ABIs"
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GITHUB_REPOSITORY: ${{ github.repository }}
      #     BRANCH_REF: "${{ steps.set_branch.outputs.branch }}"
      #   run: |
      #     git config user.email "github-actions@github.com"
      #     git config user.name "Github Actions"
      #     git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      #     git add .
      #     git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin HEAD:${BRANCH_REF})
