name: Testnet deploy after merge to main

on:
  # TODO remove me before merege
  push:
  # TODO uncomment before mereg + test
  # pull_request_review:
  #   types: [submitted]

env:
  ARBISCAN_API_KEY: ${{secrets.ARBISCAN_API_KEY}}
  ARBITRUM_TESTNET_GOERLI_RPC_URL: ${{ secrets.ARBITRUM_TESTNET_GOERLI_RPC_URL}}
  ARBITRUM_TESTNET_RPC_URL: ${{ secrets.ARBITRUM_TESTNET_RPC_URL}}
  ARBITRUM_TESTNET_SEPOLIA_RPC_URL: ${{ secrets.ARBITRUM_TESTNET_SEPOLIA_RPC_URL}}
  TESTNET_DEPLOYER_PK: ${{secrets.TESTNET_DEPLOYER_PK}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "17"
          cache: "yarn"

      - name: Determine Branch Name
        id: set_branch
        run: |
          if [[ ${{ github.event_name }} == "pull_request" ]]; then
            echo "::set-output name=branch::${{ github.head_ref }}"
          else
            branch_name=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
            echo "::set-output name=branch::$branch_name"
          fi

      - name: Install dependencies
        run: yarn install

      - name: Clear cache
        run: yarn hardhat clean --config hardhat-continuous-deployment.config.js

      - name: Compile contracts
        run: yarn hardhat compile --config hardhat-continuous-deployment.config.js

      - name: Git config
        run: git config user.name github-actions && git config user.email github-actions@github.com

      - name: Fetch repository
        run: git fetch

      - name: Deploy contracts on Arbitrum Goerli
        run: yarn upgrade:goerli --config hardhat-continuous-deployment.config.js

      - name: Deploy contracts on Arbitrum Sepolia
        run: yarn upgrade:sepolia --config hardhat-continuous-deployment.config.js

      - name: Commit
        run: |
          git add .
          git commit -m "ci(deployments): upgrade ABIs"
          git push origin "${{ steps.set_branch.outputs.branch }}"
