name: Testnet deploy after merge to main

on:
  pull_request:
    branches:
      - TT-1488-CD-deploys-to-Testnet
#   pull_request_review:
#     types: 
#       - submitted

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "17"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Clear cache
        env:
          ARBITRUM_MAINNET_RPC_URL: ${{ secrets.ARBITRUM_MAINNET_RPC_URL}}
          TESTNET_DEPLOYER_PK: ${{secrets.TESTNET_DEPLOYER_PK}}
        run: yarn hardhat clean --config hardhat-continuous-integration.config.js

      - name: Compile contracts
        env:
          ARBITRUM_TESTNET_RPC_URL: ${{ secrets.ARBITRUM_TESTNET_RPC_URL}}
          TESTNET_DEPLOYER_PK: ${{secrets.TESTNET_DEPLOYER_PK}}
          ARBISCAN_API_KEY: ${{secrets.ARBISCAN_API_KEY}}
        run: yarn hardhat compile --config hardhat-continuous-deployment.config.js

      - name: Git config
        run: git config user.name github-actions && git config user.email github-actions@github.com

      - name: Fetch repository
        run: git fetch

      - name: Deploy contracts
        env:
          ARBITRUM_TESTNET_RPC_URL: ${{ secrets.ARBITRUM_TESTNET_RPC_URL}}
          TESTNET_DEPLOYER_PK: ${{secrets.TESTNET_DEPLOYER_PK}}
          ARBISCAN_API_KEY: ${{secrets.ARBISCAN_API_KEY}}
        run: yarn upgrade:goerli --config hardhat-continuous-deployment.config.js



      - name: Commit
        run: git add . && git commit -m "Testnet deployments ABIs"

      - name: Push new ABIs
        run: git push origin
