name: Run Tests on PR Creation

on:
  pull_request:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "17"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Compile contracts
        run: yarn hardhat compile --config hardhat-continuous-integration.config.js

      - name: Run tests
        env:
          ARBITRUM_MAINNET_RPC_URL: ${{ secrets.ARBITRUM_MAINNET_RPC_URL }}
          TESTNET_DEPLOYER_PK: ${{ secrets.TESTNET_DEPLOYER_PK }}
        run: yarn test:ci
