name: Run Tests on PR Creation

on:
  pull_request:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "17"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Compile contracts
        run: yarn compile

      - name: Run tests
        env:
          TESTNET_DEPLOYER_PK: ${{ secrets.TESTNET_DEPLOYER_PK }}
          DEPLOYER_PK: ${{ secrets.DEPLOYER_PK }}
        run: yarn test ./test/unit/01-by-facet/01-term-facet.test.js
