name: Testnet deploy after merge to main

on:
  pull_request:
    branches:
      - TT-1488-CD-deploys-to-Testnet
    types:
      - closed
jobs:
#   deploy:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "17"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Compile contracts
        env:
          ARBITRUM_MAINNET_RPC_URL: ${{ secrets.ARBITRUM_TESTNET_RPC_URL}}
          TESTNET_DEPLOYER_PK: ${{secrets.TESTNET_DEPLOYER_PK}}
        run: yarn hardhat compile --config hardhat-continuous-deployment.config.js